/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Dao.PacienteDAO;
import Model.PacienteModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author jotaf
 */
public class Banco extends javax.swing.JFrame {

    /**
     * Creates new form BancoPacientes
     */
    public Banco() {

        initComponents();
        setLocationRelativeTo(null);
        DefaultTableModel modelo = (DefaultTableModel) jtPaciente.getModel();
        readJTable();

    }

    public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) jtPaciente.getModel();
        modelo.setNumRows(0);
        PacienteDAO pDao = new PacienteDAO();

        for (PacienteModel p : pDao.read()) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getCpf(),
                p.getIdade(),
                p.getPeso(),
                p.getAltura(),
                p.getTmb()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPaciente = new javax.swing.JTable();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        lblIdade = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        lblAltura = new javax.swing.JLabel();
        lblTmb = new javax.swing.JLabel();
        txtTmb = new javax.swing.JTextField();
        btnExcluir1 = new javax.swing.JButton();
        btnEditar1 = new javax.swing.JButton();
        btbCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        btnVoltar.setBackground(new java.awt.Color(255, 102, 102));
        btnVoltar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(0, 0, 0));
        btnVoltar.setText("voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("BANCO DE PACIENTES");

        jtPaciente.setBackground(new java.awt.Color(255, 255, 255));
        jtPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "Idade", "Peso", "Altura", "TMB"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPacienteMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtPacienteMouseReleased(evt);
            }
        });
        jtPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPacienteKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtPaciente);

        lblNome.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setText("Nome");

        txtNome.setBackground(new java.awt.Color(255, 255, 255));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lblCpf.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblCpf.setForeground(new java.awt.Color(0, 0, 0));
        lblCpf.setText("Cpf");

        txtCpf.setBackground(new java.awt.Color(255, 255, 255));

        txtIdade.setBackground(new java.awt.Color(255, 255, 255));
        txtIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdadeActionPerformed(evt);
            }
        });

        lblIdade.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblIdade.setForeground(new java.awt.Color(0, 0, 0));
        lblIdade.setText("Idade");

        lblPeso.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblPeso.setForeground(new java.awt.Color(0, 0, 0));
        lblPeso.setText("Peso");

        txtPeso.setBackground(new java.awt.Color(255, 255, 255));

        txtAltura.setBackground(new java.awt.Color(255, 255, 255));

        lblAltura.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblAltura.setForeground(new java.awt.Color(0, 0, 0));
        lblAltura.setText("Altura");

        lblTmb.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblTmb.setForeground(new java.awt.Color(0, 0, 0));
        lblTmb.setText("TMB");

        txtTmb.setBackground(new java.awt.Color(255, 255, 255));

        btnExcluir1.setBackground(new java.awt.Color(0, 255, 0));
        btnExcluir1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnExcluir1.setForeground(new java.awt.Color(0, 0, 0));
        btnExcluir1.setText("Excluir");
        btnExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluir1ActionPerformed(evt);
            }
        });

        btnEditar1.setBackground(new java.awt.Color(0, 255, 0));
        btnEditar1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnEditar1.setForeground(new java.awt.Color(0, 0, 0));
        btnEditar1.setText("Editar");
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });

        btbCadastrar.setBackground(new java.awt.Color(0, 255, 0));
        btbCadastrar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btbCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        btbCadastrar.setText("Cadastrar");
        btbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(241, 241, 241)
                .addComponent(btnVoltar)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdade)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCpf)
                                    .addComponent(lblNome)
                                    .addComponent(lblPeso))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblAltura)
                                    .addGap(5, 5, 5))))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTmb)
                        .addGap(44, 44, 44)
                        .addComponent(txtTmb, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btbCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar1)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir1)))
                .addGap(87, 87, 87)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar))
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCpf))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdade))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPeso))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAltura)
                            .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTmb)
                            .addComponent(txtTmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btbCadastrar)
                            .addComponent(btnEditar1)
                            .addComponent(btnExcluir1)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        Menu telamenu = new Menu();
        telamenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCadastrarActionPerformed
        // TODO add your handling code here:

        try {

            PacienteModel paciente = new PacienteModel();
            PacienteDAO pacienteDao = new PacienteDAO();

            paciente.setNome(txtNome.getText());
            paciente.setCpf(txtCpf.getText());
            paciente.setIdade(Integer.parseInt(txtIdade.getText()));
            paciente.setPeso(Double.parseDouble(txtPeso.getText()));
            paciente.setAltura(Integer.parseInt(txtAltura.getText()));
            paciente.setTmb(Double.parseDouble(txtTmb.getText()));

            pacienteDao.save(paciente);

        } catch (Exception e) {

            e.printStackTrace();

        }
        txtNome.setText("");
        txtCpf.setText("");
        txtPeso.setText("");
        txtIdade.setText("");
        txtAltura.setText("");
        txtTmb.setText("");

        dispose();
        setVisible(true);
        readJTable();


    }//GEN-LAST:event_btbCadastrarActionPerformed

    private void btnExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluir1ActionPerformed
        // TODO add your handling code here:

        if (jtPaciente.getSelectedRow() != -1) {

            try {

                PacienteModel paciente = new PacienteModel();
                PacienteDAO pacienteDao = new PacienteDAO();

                paciente.setId((int) jtPaciente.getValueAt(jtPaciente.getSelectedRow(), 0));

                pacienteDao.delete(paciente);

            } catch (Exception e) {

                e.printStackTrace();

            }
            txtNome.setText("");
            txtCpf.setText("");
            txtPeso.setText("");
            txtIdade.setText("");
            txtAltura.setText("");
            txtTmb.setText("");

            dispose();
            setVisible(true);
            readJTable();

        } else {
            JOptionPane.showMessageDialog(null, "Selcione um paciente para excluir");
        }


    }//GEN-LAST:event_btnExcluir1ActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        // TODO add your handling code here:

        try {

            PacienteModel paciente = new PacienteModel();
            PacienteDAO pacienteDao = new PacienteDAO();

            paciente.setNome(txtNome.getText());
            paciente.setCpf(txtCpf.getText());
            paciente.setIdade(Integer.parseInt(txtIdade.getText()));
            paciente.setPeso(Double.parseDouble(txtPeso.getText()));
            paciente.setAltura(Integer.parseInt(txtAltura.getText()));
            paciente.setTmb(Double.parseDouble(txtTmb.getText()));
            paciente.setId((int) jtPaciente.getValueAt(jtPaciente.getSelectedRow(), 0));

            pacienteDao.update(paciente);

        } catch (Exception e) {

            e.printStackTrace();

        }
        txtNome.setText("");
        txtCpf.setText("");
        txtPeso.setText("");
        txtIdade.setText("");
        txtAltura.setText("");
        txtTmb.setText("");

        dispose();
        setVisible(true);
        readJTable();


    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void jtPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPacienteMouseClicked
        // TODO add your handling code here:

        if (jtPaciente.getSelectedRow() != -1) {

            txtNome.setText(jtPaciente.getValueAt(jtPaciente.getSelectedRow(), 1).toString());
            txtCpf.setText(jtPaciente.getValueAt(jtPaciente.getSelectedRow(), 2).toString());
            txtIdade.setText(jtPaciente.getValueAt(jtPaciente.getSelectedRow(), 3).toString());
            txtPeso.setText(jtPaciente.getValueAt(jtPaciente.getSelectedRow(), 4).toString());
            txtAltura.setText(jtPaciente.getValueAt(jtPaciente.getSelectedRow(), 5).toString());
            txtTmb.setText(jtPaciente.getValueAt(jtPaciente.getSelectedRow(), 6).toString());

        }
    }//GEN-LAST:event_jtPacienteMouseClicked

    private void jtPacienteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPacienteMouseReleased
        // TODO add your handling code here:

        if (jtPaciente.getSelectedRow() != -1) {

            txtNome.setText(jtPaciente.getValueAt(jtPaciente.getSelectedRow(), 1).toString());
            txtCpf.setText(jtPaciente.getValueAt(jtPaciente.getSelectedRow(), 2).toString());
            txtIdade.setText(jtPaciente.getValueAt(jtPaciente.getSelectedRow(), 3).toString());
            txtPeso.setText(jtPaciente.getValueAt(jtPaciente.getSelectedRow(), 4).toString());
            txtAltura.setText(jtPaciente.getValueAt(jtPaciente.getSelectedRow(), 5).toString());
            txtTmb.setText(jtPaciente.getValueAt(jtPaciente.getSelectedRow(), 6).toString());

        }
    }//GEN-LAST:event_jtPacienteMouseReleased

    private void jtPacienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPacienteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPacienteKeyReleased

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
            
        txtNome.setText("");
        txtCpf.setText("");
        txtPeso.setText("");
        txtIdade.setText("");
        txtAltura.setText("");
        txtTmb.setText("");
        
    }//GEN-LAST:event_formMouseClicked

    private void txtIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Banco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbCadastrar;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnExcluir1;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtPaciente;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblTmb;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtTmb;
    // End of variables declaration//GEN-END:variables
}
